[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/appcenter"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[prune]
  go-tests = true
  unused-packages = true
